### ISSUE TITLE
what is Liquidator contract's address in BSC mainnet after 2022/2/22?

### ISSUE THREAD

**Issue by readygo67** [VenusProtocol/venus-protocol#106]

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by chechu** [comment]
The current liquidator contract on BNB chain: https://bscscan.com/address/0x0870793286aaDA55D39CE7f82fb2766e8004cF43

You can see the rest of the relevant addresses here: https://docs-v4.venus.io/deployed-contracts/core-pool
