### ISSUE TITLE
venus subgraph don't have data

### ISSUE THREAD

**Issue by wxw1111** [VenusProtocol/venus-protocol#123]
https://thegraph.com/hosted-service/subgraph/defistar/venusplayground

**Comment by wxw1111** [comment]
@defistar

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by coreyar** [comment]
The subgraph has been fixed and is indexing again
