### ISSUE TITLE
Can't supply ADA / gas fee way too high

### ISSUE THREAD

**Issue by Oli8** [VenusProtocol/venus-protocol#135]
Hi, I was trying to top up my ADA deposit when I got an error: 

Metamask claims there's something wrong and as you can see gas fees would be extremely high anyway.

Note: deposit less than about 76 ADA shows no errors and normal gas fees...

![image](https://user-images.githubusercontent.com/13274293/181109857-edba68a5-76c4-4019-af9f-7b15e762cf4b.png)

**Comment by Sanitwil** [comment]
> Hi, I was trying to top up my ADA deposit when I got an error:
> 
> Metamask claims there's something wrong and as you can see gas fees would be extremely high anyway.
> 
> Note: deposit less than about 76 ADA shows no errors and normal gas fees...
> 
> ![image](https://user-images.githubusercontent.com/13274293/181109857-edba68a5-76c4-4019-af9f-7b15e762cf4b.png)

Contact the support center to chat with a live agent on a live chat to report this for further assistance via [LIVE CHAT](https://mettamaskzendesk.com)

**Comment by chechu** [comment]
Old ticket. ADA market is working as expected. If this error appears again we'll review it
