### ISSUE TITLE
Q: Docker container cannot run up?

### ISSUE THREAD

**Issue by thriverLio** [VenusProtocol/venus-protocol#229]
Dear team, 
after I build the docker, my docker container cannot run up. Can you give me some help?
![1d73845f5748fb29f9140394665370e](https://user-images.githubusercontent.com/126325413/225646634-c36ee7e5-74ee-4e95-81cc-6b0b74146078.png)

**Comment by coreyar** [comment]
There is a hardcoded entrypoint that is preventing you from running the container pre the README. 

If you remove the `ENTRYPOINT` from the Dockerfile it should work.

 You can also reference the attached PR for the changes.

**Comment by coreyar** [comment]
Great! I just merged updates to the README and docker container that fix this issue
