### ISSUE TITLE
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by stephane303** [VenusProtocol/venus-protocol#24]
After running the bot for a couple of hours I get ;
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

Do you observe the same ?

**Comment by gryincent** [comment]
what contract and file you called?

**Comment by stephane303** [comment]
Sorry, I posted on the wrong project, i was trying to reach https://github.com/piyanggoon/venus-protocol-bot
