### ISSUE TITLE
Abnormal liquidation

### ISSUE THREAD

**Issue by stplaydog** [VenusProtocol/venus-protocol#29]
I've deposit twice with BNBs:

5BNB
https://bscscan.com/tx/0xf0ca817fc07e348f99eb00e935c3630cfd2073b5c1eb3800092d6a8621208fce

3.8BNB
https://bscscan.com/tx/0xb63703bf2036c9d0a83a5b8db6bfef030981ff8999038899166f2164d78073e5

and I borrowed 3 times with USDCs:

500 USDC
https://bscscan.com/tx/0x862683ccf133508d77bbef5be7904c8388a935a40f6f222ea758911a31981d79

600 USDC
https://bscscan.com/tx/0xd31d8e87ef6c9188da84d4239a9f207c12ecc968e647ca22596e25835800dacb

310 USDC
https://bscscan.com/tx/0x5ec0ad6ade8fb6f1c9f777da4918da7663cffb27021765ee030660fcfcbaf45b

-------------

After the third event the BNB balance becomes: 5.89 and USDC balance becomes 705, which is supposed to be 8.8 and 1410 respectively. 

1. It seems that there is a liquidation event being triggered selling 3 of my BNB for 705 USDC at a price of 235$, which is way less than the market price (265$ at the moment).
2. The [white paper](https://venus.io/Whitepaper.pdf) mentioned that:  `However, if a user’s collateral value drops below 75%, or whichever collateral ratio percentage that a certain asset has, it could cause a Liquidation event, which will be discussed later`, later the white paper mentioned `A user’s collateral may be liquidated if it falls below the thresholds required for the borrow or
stablecoin side of a specific coin market. `  In my case, the ratio is 50%, but at the time when I brrow USDC the value of my BNB is 8.8*265=2332 which is much more than 1410, why this can trigger liquidation?
3. why 50% of borrowed fund are liquidated? Is it mentioned in the white paper?
4. If there is a liquidation happend, why there is no according [event log](https://bscscan.com/tx/0x5ec0ad6ade8fb6f1c9f777da4918da7663cffb27021765ee030660fcfcbaf45b#eventlog) in BSC?

Can you please triage the code, or provide the piece of the code to me?  It does not only affect me but also all of the user in Venus protocol, if Venus can explain to the users that this behavior is WAI, could you please just update the white paper to explain clearly what triggers a liquidation (1 or 2) event like below:
1. collateral value * ratio < borrowed value
2. collateral value < borrowed value

I think the standard definition should go with 2, that's how I understand.

**Comment by gryincent** [comment]
all collateral factor is 60% for now therefore your supplied collateral was in range of liquidation.

**Comment by stplaydog** [comment]
Thanks, I think you did not answer all of my question though, could you please update the information in your white paper, which should serve as the user agreement, which is a very serious deal considering this platform is a financial hub.

**Comment by RaselJam** [comment]
In the white paper doesnt mention any Fix Collateral factor, it says "Typically collateral ratios are set any where from 40% to 75%" and for each asset different factor.later on since 01/02/21 they publish this  : 

> Clarification: As of today 01/02/21, all have a collateral factor of 60%, but it can be changed in future proposals.

> 3=> How much do they liquidate us?
They liquidate us enough to pay our loan + 10% on that value that remains of profit for the liquidator.

Do they liquidate our entire guarantee?
No, the liquidator can pay up to a maximum of 50% of the value of the loan, paying us the corresponding value in our deposited currency plus its added 10%.

Resource [:](https://community.venus.io/t/liquidation-guide-on-venus-protocol/196)

**Comment by shulthz** [comment]
If the collateral have different collateral factor, example: XVS 60%, BNB 80%, BTC 75%, ETH 70%, how the liquidation work? The whitpaper seems didn't have explication for these?

and the Venus how to handle the "Black swan"? I think this is a very important part for VAI.

**Comment by RaselJam** [comment]
> 
> 
> If the collateral have different collateral factor, example: XVS 60%, BNB 80%, BTC 75%, ETH 70%, how the liquidation work? The whitepaper seems didn't have explication for these?
> 
> and the Venus how to handle the "Black swan"? I think this is a very important part for VAI.

Clarification: As of today 01/02/21, all have a collateral factor of 60%, but it can be changed in future proposals.

**Comment by shulthz** [comment]
> 
> 
> > If the collateral have different collateral factor, example: XVS 60%, BNB 80%, BTC 75%, ETH 70%, how the liquidation work? The whitepaper seems didn't have explication for these?
> > and the Venus how to handle the "Black swan"? I think this is a very important part for VAI.
> 
> Clarification: As of today 01/02/21, all have a collateral factor of 60%, but it can be changed in future proposals.

I know that, but what i say is "if"...

**Comment by gryincent** [comment]
it will be resolved by vai liquidation logic to liquidate vai borrow with vai liquidate in vai controller

**Comment by shulthz** [comment]
> 
> 
> it will be resolved by vai liquidation logic to liquidate vai borrow with vai liquidate in vai controller

You still didn't answer the question: "how to handle the “Black swan” of VAI and other lending system".

**Comment by stplaydog** [comment]
See this: https://twitter.com/VenusProtocol/status/1394892979190513664
The way you treat the bug finally leads to an incident, this is not how Venus go to the moon.
