### ISSUE TITLE
A leveraged voting power question and problem

### ISSUE THREAD

**Issue by shulthz** [VenusProtocol/venus-protocol#31]
Question:
If the xXVS can vote, that’s meaning the collateral have the vote power, a leveraged voting power, is it fair for the XVS holder who didn’t make a leverage?

Example:

   1. I only have 10 XVS,
   2. XVS pirce: 65 USDT,
   3. 60% collateral factor,
   4. I lend 390 USDT using XVS as the collateral in Venus,
   5. I used these 390 USDT to buy XVS in pancake or CEX, 390/65=6 XVS,
   6. Collateralize these 6 XVS in Venus and lend some USDT again,
   7. Use the new lending USDT to buy XVS in pancake or CEX,
   8. Collateralize these new buying XVS in Venus and lend some USDT again
   9. Repeat the opretion 4-8.

Then i will make a 1.47× leveraged XVS with 60% collateral factor, and i will have 2.4× leveraged voting power.

This is what happend in MAKERDAO and YFI, and solved, i want to know Venus how to solve this problem with the xXVS can vote?

Thanks.

https://community.venus.io/t/a-leveraged-voting-power-question-and-problem/539

**Comment by jinjiangcc** [comment]
Why did the code test fail again? Team skills need to be improved

**Comment by jinjiangcc** [comment]
Why do technical teams always make elementary mistakes in their code

**Comment by gryincent** [comment]
vXVS voting power already integrated in master and will deploy in further proposal

**Comment by shulthz** [comment]
> 
> 
> vXVS voting power already integrated in master and will deploy in further proposal

You didn't answer my question: "the leveraged voting power".
