### ISSUE TITLE
Math Error on BUSD Withdrawals

### ISSUE THREAD

**Issue by Fergal91** [VenusProtocol/venus-protocol#331]
When removing BUSD that was previously used for collateral I get a math error for any value greater than 1.

**Comment by chechu** [comment]
Deprecation of BUSD market started already. See https://app.venus.io/#/governance/proposal/161. You have to monitor liquidity and withdraw your BUSD when liquidity is available (it means when borrowers repay their loans or they are liquidated). If you try to withdraw more than the available liquidity you will get an error
