### ISSUE TITLE
Repay With Collateral Feature is Missing

### ISSUE THREAD

**Issue by michael-spengler** [VenusProtocol/venus-protocol#38]
aave and compound offer a "Repay With Collateral Feature" which allows users to repay some borrowings even if they do not have the corresponding liquidity in their browserwallet.

I could not find such a feature in the venus dashboard. 

It would be great if you could help me out. I would also offer some pair programming to get this implemented together if you wish.

**Comment by gryincent** [comment]
feature not added in UI but it has feature in contract already.
you can check in smart contract here
repayBorrowBehalf
https://bscscan.com/address/0x57a5297f2cb2c0aac9d554660acd6d385ab50c6b#writeProxyContract
https://github.com/VenusProtocol/venus-protocol/blob/master/contracts/VBep20Delegator.sol#L134
