### ISSUE TITLE
How to Supply Assets from a smart contract on User action but maintain ownership of vtokens with contract.

### ISSUE THREAD

**Issue by BlockChainBobC** [VenusProtocol/venus-protocol#41]
I am looking for a quick boilerplate example of how to mint and thus supply assets to the protocol from another smart contract when a user takes an action, causing the user to pay the gas fees, while maintaining the contract as the owner, controller and beneficiary of the minted vtokens. I'm running into some issues using different compiled versions of solidity so simply importing the interface is not working as expected, so to get me up to speed fast I was wondering if there were any code examples or other projects that have implemented anything like this... 

I have to be honest with you, I am not a supreme Solidity wizard. I am still new to blockchain.  I am a php WordPress guy and am trying to build something that brings crypto and yield to regular folks... The normies.. In fact I am working with another dev on this and we are trying to get this out the door fast so any help or direction you can offer would be a lot of help.

I have a few buddies that have been thinking of adding Venus to their future dev workflows, perhaps having some boilerplate examples would be useful to the community to bring dapps that use the protocol to market faster.

**Comment by bonhardt** [comment]
First the user have to approve your custom contract on the underlying asset lets say you will supply "XVS"
your custom contract then must have a function that takes this token from the user when he call a specific function lets say "mySupplyFunction"

mySupplyFunction will have to contain at least these steps

XVS.transferFrom(useraddress, yourcontractaddress, amount) _( transfers XVS to your custom contract )_
XVS.approve(vXVS, amount); _( approves vXVS to be able take the XVS from the custom contract )_
vXVS.mint(amount) _( supplies the XVS amount and the custom contract will receive the vToken )_
