### ISSUE TITLE
1. Supply/Borrow number error 2. venus protocol requires too many gas fees not showing the account's whole situation correctly. 3. Can't borrow/lend any money on venus.

### ISSUE THREAD

**Issue by tera04162** [VenusProtocol/venus-protocol#44]
Briefly my Symptoms 

**1.  stopped at this supply/borrowing numbers, not updating my numbers on venus since yesterday.**

![now venus](https://user-images.githubusercontent.com/44395082/118172483-64c20480-b467-11eb-91fd-9d223b287bfa.png)

**2. required too many gas fees when try to withdraw the balance on metamask.
and not showing any information on trustwallet.**

![캡처_2021_05_13_23_09_21_974](https://user-images.githubusercontent.com/44395082/118172532-75727a80-b467-11eb-87e8-e2e8100b6d82.png)

![캡처_2021_05_13_23_10_00_47](https://user-images.githubusercontent.com/44395082/118172555-799e9800-b467-11eb-8055-ce1cf39dd87c.png)

**3. only can see the xvs rewards going up on app.venus.io through metamask. but can't lead any information on finance.venus.** 

tried every methods including changing wallet/nodes and deleting caches and reinstall metamask/trust wallets But only venus dapp did not work and showing only old data. Always just circling gears on venus.finance/app.

![캡처_2021_05_14_02_09_14_229](https://user-images.githubusercontent.com/44395082/118172624-8cb16800-b467-11eb-8414-c1fa2ba3e619.png)

So can't repay borrow even with proper usdt on venus. The repay key color always gray just like the past time's balance. 

![캡처_2021_05_14_11_26_17_106](https://user-images.githubusercontent.com/44395082/118211544-411eae80-b4a7-11eb-98fd-eef7681eff35.png)

Also can't withdraw any. Literally lending/borrowing is stuck now. (working well on Cream finance. Just not working on venus)

**With help of danny and mike from venus team through telegram, we got some clues.** 

After my reporting, they said **this error could be related with oracle update as kind of smart contract error.** 
The log could be the **"getAccountLiquidity(account) from Comptroller.sol"** 

I hope the Venus team find the way to rescue my BNB and XVS safely. And I didn't do anything wrong(of course not hacking like that!), just did lending/borrowing. Don't hate me and my address. :D 

my address is 

**https://bscscan.com/address/0x0150Bc2A8df90328C6b957eD03A8725462d0b4bB**

If I could get some Bug-Bounty Rewards, that will be helpful, as response for melting my account by captured on Venus through this down-trend market. But most importantly, after solving the smartcontract error issue. Because sometimes few flaws like the price oracle errors could collapse the whole project.

-

I appreciate the whole help from the community.  

Sincerely.

**Comment by bonhardt** [comment]
i will write for you here also, 

it is cause the chainlink Oracle does not have price for CAN, and without having price the liquidity calculation in venus is broken for those users who have CAN enabled as collateral, the other user issue you mention has also CAN enabled.

I reported this bug directly to Venus Team 3 days ago so hopefully they are "working" on it.

**Comment by tera04162** [comment]
Hi~ Good to hear your thought about Venus problem nowadays. Ironically I didn't borrow/lend CAN token, but might be approved it as collateral (at that time, for just in case). 

I think it's better to inform this issue for users of Venus by Venus team. But still I and some members who got stuck their money didn't get any official answer from them while market is going down. Hopefully they get to do right thing for users quickly.

**Comment by marcuscent** [comment]
I have a similar problem. I can't withdraw any of my BNB from Venus. The UI won't allow me to enter the number of BNB I want to withdraw. It's not used for collateral and I have no borrowing. I just want to withdraw back to metamask. Any ideas on how to resolve?

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by C3mkal** [comment]
#157 #169 #180 #179 #178
