### ISSUE TITLE
Governance Proposal: Unlock user funds in vBUSD and vUSDT

### ISSUE THREAD

**Issue by Smyak** [VenusProtocol/venus-protocol#45]
**Background**
On April 12th DeFireX user vBUSD and vUSDT tokens stuck at upgradable smart-
contracts (additional info and governance proposal here: https://community.venus.io/t/proposal-defirex-stuck-money-recovery-help-needed-from-the-venus-community-team/676). 

Contracts with locked funds are:
1. 0x3b1a4f61bd3d7301edbd3ea2a5e05ede8dda812d - vBUSD
2. 0x22b433402b65dccbe79fe66b4990a2569ab01572 - vUSDT

Upgradable-smart contracts:
0x987f04dece1c5ae9e69cf4f93d00bbe2ca5af98c
0xb7552a0463515bda8b47ab7503ca893e52c58df8

Current temporary implementation 0x9c8a83a0bfeb560dfac404132827f3c38f14d1e1 without function to withdraw user funds.

ProxyAdmin to control upgradable-smart contracts
0x98d6c44d2b25cac7c364edb7e992a77afcf3f795

changeProxyAdmin errors that leads to funds-lock
https://bscscan.com/tx/0xa295adf5250f650ed106f31c6f12fc6ff774b896f8783f97d275720810562069#eventlog
https://bscscan.com/tx/0x24c0aad2931a203f933aceeb52344196f6ea6de55e2be7f8261f85a0a290c69a#eventlog

**Proposed solution**
Update the implementation of vBUSD and vUSDT contracts. Add new function that will allow to unlock stuck funds.
Suggested implementation for vTokens
Forked Venus protocol: https://github.com/DeFireX/venus-protocol/blob/master/contracts/VToken.sol#L145
Deployed implementation on BSC: https://bscscan.com/address/0x1115851ee76b5f1c1ea78d20e6beb9a9f83b11af#code
Additional github repository with all required files and tests in one place:
https://github.com/DeFireX/venus-proposal

Also we created a contract that can be used for governance proposal, users can delegate votes to this contract
Source code: https://github.com/DeFireX/venus-proposal/blob/main/contracts/Proposal.sol
Deloyed contract on BSC: https://bscscan.com/address/0xde582596e0afcd2f33894a38d549c0d95a703c05#code

**Comment by rtarnaud** [comment]
i have some questions about the Venus proposal. You (or someone else from your team) said that Binance would delegate enough votes on Venus to pass that proposal. However, the post on the Venus community forum incentivizes users to delegate their XVS to the DeFireX address. So should I understand that Binance will not delegate any votes after all? And that the fate of the proposal rests entirely on the community?

**Comment by Smyak** [comment]
> i have some questions about the Venus proposal. You (or someone else from your team) said that Binance would delegate enough votes on Venus to pass that proposal. However, the post on the Venus community forum incentivizes users to delegate their XVS to the DeFireX address. So should I understand that Binance will not delegate any votes after all? And that the fate of the proposal rests entirely on the community?

Delegating votes from Binance may require too much time. We use any chances to return funds back as soon as possible.

**Comment by kkirka** [comment]
Resolved in VIP-44
