### ISSUE TITLE
Accounts with legacy CAN associated broken after oracle update.

### ISSUE THREAD

**Issue by whitematrix62** [VenusProtocol/venus-protocol#46]
After the oracle update, accounts that either 1.supplied CAN, 2.borrowed CAN or 3.enabled CAN as collateral becomes unusable. 
These are legacy positions that have not been completely removed from Venus and still affects accounts that interacted with CAN. 
It affects not only the ui such as https://app.venus.io/ and https://venus.finance/app. But also direct contract interaction.

**Comment by whitematrix62** [comment]
From issue report #44, it seems that the problem is not limited to accounts that has CAN associated with it.

**Comment by bonhardt** [comment]
it is cause the chainlink Oracle does not have price for CAN, and without having price the liquidity calculation in venus is broken for those users who have CAN enabled as collateral, the other user issue you mention has also CAN enabled.

I reported this bug directly to Venus Team 3 days ago so hopefully they are "working" on it.

**Comment by whitematrix62** [comment]
> it is cause the chainlink Oracle does not have price for CAN, and without having price the liquidity calculation in venus is broken for those users who have CAN enabled as collateral, the other user issue you mention has also CAN enabled.
> 
> I reported this bug directly to Venus Team 3 days ago so hopefully they are "working" on it.

I didn't see any CAN supplied or borrowed and thought it's independent of CAN. So it seems it's CAN related after all.

**Comment by bonhardt** [comment]
https://bscscan.com/address/0xfd36e2c2a6789db23113685031d7f16329158384#readProxyContract
on this contract you can check the address which market has enabled as collateral getAssetsIn function

![image](https://user-images.githubusercontent.com/26343376/118361636-a26c7d80-b58c-11eb-902d-e1c3a24b8226.png)

you can see he have the Venus CAN market address in the list which means he had it enabled in the past and thats causing the error

**Comment by whitematrix62** [comment]
Has the project been abandoned?

**Comment by gryincent** [comment]
In order to solve this issue, should set price for CAN in chainlink as 0.00001 under value $0.01 cent due to the market already added unable to remove or update current priceOracle to handle except for unsupported asset

**Comment by whitematrix62** [comment]
Will chainlink add CAN just to fulfil venus oracle needs? Can the oracle be reverted back to BAND till the issue is fixed? What's going to happen to all the funds that are currently stuck due to this?

**Comment by bonhardt** [comment]
> Will chainlink add CAN just to fulfil venus oracle needs? Can the oracle be reverted back to BAND till the issue is fixed? What's going to happen to all the funds that are currently stuck due to this?

they dont need chainlink for that, the venus oracle that was deployed by venus which reads from chainlink, has a function to set a fixed DirectPrice for a certain asset which can solve this issue without bothering chainlink at all.

**Comment by kkirka** [comment]
Closing as stale. If your issue has not been resolved, please leave a comment
