### ISSUE TITLE
How run Venus in local?

### ISSUE THREAD

**Issue by dhavalmp194** [VenusProtocol/venus-protocol#60]
hello i am trying to deploying contracts on my own and run it on local
but i am confused that what contract I should deploy first?
is it VBep20, VBep20Delegator, VBep20Delegate?

**Comment by coreyar** [comment]
We had added `hardhat-deploy` with scripts that deploy the contracts when your run a local hardhat node. The scripts are located in the `deploy` directory. You can take advantage of those scripts to deploy them automatically when running the node or reference them to understand the order of deployment
