### ISSUE TITLE
Not able to add/remove liquidity in pools involving XVS and SXP tokens. Strategy used behind this is of venus protocol

### ISSUE THREAD

**Issue by w3villa-neha** [VenusProtocol/venus-protocol#64]
Link to the log file
https://testnet.bscscan.com/tx/0xaaa9cdf1280bc1823fa5f03668af74313a5e18c4cf4fe62d14e29d8de298a4c7

**Comment by w3villa-neha** [comment]
We are using venus protocol in our pools tokens. What we have done is we created ITokens for all underlying pools tokens ex - our pool is (BNB, SXP, USDC) and corresponding ITokens are (IBNB,ISXP,IUSDC). These ITokens are interacting with strategy contract which internally connecting with venus Token of underlying token i.e. (vBNB,vSXP,vUSDC). 
Our add liquidity function was working fine previously but now it suddenly start throughing errors. All the functionalities related to SXP token like swapping, add liquidity and remove liquidity is not working. The same issue we got with XVS previously so we replaced it with SXP but now it is also not working. The transaction was failed at the point where it is interacting with venus protocol contracts. The transaction fails inside https://testnet.bscscan.com/address/0x74469281310195a04840daf6edf576f559a3de80 this contract (vSXP)

**Comment by w3villa-ashish** [comment]
Hi Team, Please update on above issue.

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by chechu** [comment]
Old ticket, based on a legacy deployment on testnet. If the problem still exists with the new deployment (see addresses [here](https://docs-v4.venus.io/deployed-contracts/core-pool)), we'll review it
