### ISSUE TITLE
Web page reloads every 3 secs

### ISSUE THREAD

**Issue by alvaroscelza** [VenusProtocol/venus-protocol#82]
I've discovered https://app.venus.io/ and wanted to give it a try but found that it's website behaves weird: it reloads every 3 seconds, making it impossible to use.

![image](https://user-images.githubusercontent.com/12629918/141027167-abaaa947-bdca-456a-9001-2060ef53ff8d.png)

This happens in Google Chrome Version 95.0.4638.69 (Build oficial) (64 bits)

**Comment by xueyouyongdeyu** [comment]
对头，连接钱包后就可以进入网站，速度还挺快，

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by coreyar** [comment]
We have rebuilt the frontend with new mechanisms for fetching and refreshing data. Please retest and if it continues to be an issue feel free to open a PR on the [frontend repo](https://github.com/VenusProtocol/venus-protocol-interface) if the problem persists
