### ISSUE TITLE
Everyone is concerned with the direction of Venus.  No one is happy as investors and the price is showing.

### ISSUE THREAD

**Issue by Thenewguy911** [VenusProtocol/venus-protocol#84]
Who is actually in charge and how do investors contact them.  We have been told binance smart chain is in charge, but who is that?

**Comment by Thenewguy911** [comment]
https://community.venus.io/t/what-is-happening-with-venus/2008

Please read.  We are not happy with anything thats happening from this member who is named Danny.  We need a professional staff not some investor.  Many investors are selling in our group.

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
