### ISSUE TITLE
error code3 : SXPTROLLER_REJECTION

### ISSUE THREAD

**Issue by Daehyun-Bae** [VenusProtocol/venus-protocol#93]
hi,

While reading the error code guide in the docs, I just wonder that what does error 3: SXPTROLLER_REJECTION means.
especially, what is SXPtroller? I cannot find out any information.

sincerely,
thank you.

**Comment by swarna1101** [comment]
Error code 3: SXPTROLLER_REJECTION is an error that may be returned by a smart contract that is using the Venus Protocol. It indicates that the action being taken by the contract has been rejected by the SXPtroller, which is a smart contract that serves as the controller for the Venus Protocol.

The SXPtroller contract is responsible for enforcing the rules and policies of the Venus Protocol, including the lending and borrowing of assets on the platform. It has the ability to approve or reject certain actions taken by other contracts that interact with the Venus Protocol.

The SXPTROLLER_REJECTION error may be returned in a variety of situations, such as when a contract attempts to borrow an asset that it is not allowed to borrow according to the rules of the Venus Protocol, or when a contract attempts to take an action that is not permitted according to the policies of the SXPtroller.

**Comment by coreyar** [comment]
This is an error from Fortress loans. I'm going to close this issue because it is not an issue with Venus. 
Here is a [link](https://docs.fortress.loans/protocol-documentation/ftokens/error-codes) to their error codes.


You may follow up with Fortress if further assistance is required.
